{% set name = "notifiers" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/notifiers-{{ version }}.tar.gz
  sha256: 56d84d91bb0b272c80a16535b7e2142ac05910f661313da576d8384eaa6852a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >=7.0
    - jsonschema >=3.0.0
    - python >=3.6
    - requests >=2.21.0
    - rfc3987 >=1.3.8

test:
  imports:
    - notifiers
    - notifiers.providers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/notifiers/notifiers
  summary: The easy way to send notifications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
